### ISSUE TITLE
Palette issue introduced in v4.0.0

### ISSUE THREAD

**Issue by mike8699** [RoadrunnerWMC/ndspy#6]
It seems like something major changed in the code that handles reading alpha values from palettes between version 3.0.0 and 4.0.0. I've been using 3.0.0 on a project, and I recently tried to upgrade to 4.0.0 so I can make use of the new CLIs it introduced. 

One of the things I'm doing is extracting an image from an NDS rom (The title screen of Zelda Phantom Hourglass US, to be exact). This is what ndspy 3.0.0 outputted for a palette (which is correct):
![output3](https://user-images.githubusercontent.com/91105575/172061418-c16d4085-6570-4bec-b28b-59e0d0f833e5.png)
(Code used to extract is here https://gist.github.com/mikeoss/322a45ad01ed48b5a98bc638abcb6398)

and this is what ndspy 4.0.0 outputted after updating the code to account for API changes to the `color` and `graphics2D` modules (with messed up alpha values):
![output4](https://user-images.githubusercontent.com/91105575/172061451-0bdcdacd-c2cc-4a81-9e4e-527146d2379a.png)
(Code used to extract is here https://gist.github.com/mikeoss/6e92e6543fc04014b5a9c8df7531034b)

**Comment by mikeoss** [comment]
I just noticed the RGB values for the pixel values when using ndspy v4.0.0 were off by a factor of 8.

**Comment by mikeoss** [comment]
I just noticed the RGB values for the pixel values when using ndspy v4.0.0 are off by a factor of 8. So after extracting, I simply multiplied each value by 8 before writing the pixel to the PIL Image, and it appears to be working now. I don't know why this works (and I am not very familiar with how graphics work in general, if you can tell 😄), and if the initial error was the fault of my code or ndspy. Either way, this is resolved for me, feel free to close if this isn't an ndspy problem @RoadrunnerWMC .

**Comment by RoadrunnerWMC** [comment]
Sorry for the late response. Yeah, the function behaves differently now -- it returns RGB5A1 tuples (i.e. each RGB channel is 0-31, and the alpha channel is just 0-1) instead of RGBA8 tuples (i.e. all channels are 0-255). You can convert them with `ndspy.color.expand()`, or `ndspy.color.convert(..., ColorFormat.TUPLE_RGB5A1, ColorFormat.TUPLE_RGBA255)`. Or just multiply the channels by 8, as you're doing.
